# -*- coding: utf-8 -*-
"""paper_kr_finbert

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t9gFxD9igpImh9qMPEf2mPEsJY1RlomQ

### . Import library
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# import seaborn as sns
# sns.set( style="whitegrid" )
import math

import requests

"""###. Define Function"""

API_URL = "https://api-inference.huggingface.co/models/snunlp/KR-FinBert-SC"
headers = {"Authorization": "Bearer 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"}

def query( content ):
  payload = {}
  payload["inputs"] = content

  response = requests.post(API_URL, headers=headers, json=payload)

  return response.json()

"""###. Load Plain News Data / ETL"""

news = pd.read_csv( "/content/drive/MyDrive/Colab Notebooks/Paper/newsdata/news_weekdays.csv" )

len(news)

"""###. Tag Sentiment"""

# news["sentiment"] = "-"
# news["positive"] = 0
# news["negative"] = 0
# news["neutral"] = 0

for d in news["date"].unique():

  daily_news = news[news["date"]==d]

  for i in range( 0, daily_news["date"].count() ):

    if daily_news.iloc[i, -5] == "-":

      title = daily_news.iloc[i, 4]

      sentiment = query( title )

      row = pd.DataFrame( sentiment[0] )

      positive = row[row["label"]=="positive"].iloc[0, 1]
      negative = row[row["label"]=="negative"].iloc[0, 1]
      neutral = row[row["label"]=="neutral"].iloc[0, 1]

      news.loc[daily_news.index[i], "positive"] = positive
      news.loc[daily_news.index[i], "negative"] = negative
      news.loc[daily_news.index[i], "neutral"] = neutral

      news.loc[daily_news.index[i], "sentiment"] = "done"

      # print( d, " : ", content, " : ", sentiment )
      print( d," : ", i, " : ", title, " : ", positive, " : ", negative, " : ", neutral )
      # print( d," : ", i )
      # print( "------------------------------------------\n\n" )

"""###. Insert Sentiment Result"""

news.to_csv( "/content/drive/MyDrive/Colab Notebooks/Paper/newsdata/news_weekdays_KR_FinBERT.csv", index=False )

news = pd.read_csv( "/content/drive/MyDrive/Colab Notebooks/Paper/newsdata/news_weekdays_KR_FinBERT.csv" )

news



for d in news["date"].unique():

  daily_news = news[news["date"]==d]

  for i in range( 0, daily_news["date"].count() ):

    positive = daily_news.iloc[i, -3]
    negative = daily_news.iloc[i, -2]
    neutral = daily_news.iloc[i, -1]

    if positive > negative:
      if positive > neutral:
        news.loc[daily_news.index[i], "sentiment"] = "positive"
      else:
        news.loc[daily_news.index[i], "sentiment"] = "neutral"
    elif negative > positive:
      if negative > neutral:
        news.loc[daily_news.index[i], "sentiment"] = "negative"
      else:
        news.loc[daily_news.index[i], "sentiment"] = "neutral"
    else:
      news.loc[daily_news.index[i], "sentiment"] = "neutral"

    # print( d," : ", i, " : ", daily_news.iloc[i, -4], " : ", positive, " : ", negative, " : ", neutral )
      # print( d," : ", i )
      # print( "------------------------------------------\n\n" )

news.groupby("sentiment")["sentiment"].count()

news.groupby("sentiment")["sentiment"].count()

news.to_csv( "/content/drive/MyDrive/Colab Notebooks/Paper/wide_news/news_kr_finbert_temperature_0.2.csv", index=False )



for d in news["date"].unique():

  daily_news = news[news["date"]==d]

  for i in range( 0, daily_news["date"].count() ):

    positive = daily_news.iloc[i, -3]
    negative = daily_news.iloc[i, -2]
    neutral = daily_news.iloc[i, -1]

    if positive > negative:
      news.loc[daily_news.index[i], "sentiment"] = "positive"
    elif negative > positive:
      news.loc[daily_news.index[i], "sentiment"] = "negative"

    # print( d," : ", i, " : ", daily_news.iloc[i, -4], " : ", positive, " : ", negative, " : ", neutral )
      # print( d," : ", i )
      # print( "------------------------------------------\n\n" )

news.to_csv( "/content/drive/MyDrive/Colab Notebooks/Paper/wide_news/news_kr_finbert_temperature_0.2_binary.csv", index=False )



